#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AnimationActivities.Resource", IsApplication=true)]

namespace AnimationActivities
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int Pushdown_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Pushdown_out = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Pushup_in = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Pushup_out = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Side_in_left = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int Side_in_right = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int Side_out_left = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int Side_out_right = 2130968583;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int bottomtotop = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int lefttoright = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int righttoleft = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int textView1 = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int toptobottom = 2131099652;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int bottomtotop = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Lefttoright = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Righttoleft = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Toptobottom = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
